### PR TITLE
Enhanced Repositories UI [Jetpack Compose].

### PR DESCRIPTION
**Pull request by prasoonsoni**
# Enhanced UI of repository activity as per the theme. 👍
Solved issue #26 .
### Screenshot
Screenshot_20211005-004020_GitPositive

### CODE REVIEW

**Comment by gaganmalvi** [comment]
Doesn't the Your Repositories thing look too big?

**Comment by prasoonsoni** [comment]
Do you Mean the text size?

**Comment by gaganmalvi** [comment]
Yes

**Comment by gaganmalvi** [comment]
Also, whilst you're at this, please check the alignment of the FABs with the cards. They seem a bit off

**Comment by rishuyadav** [comment]
Hey @prasoonsoni gr8 work, we have a suggestion can u please remove that vibrating effect on button click, from pov of user it seems not very good when the device vibrates with every click, if u can remove that vibrating effect it would be great

**Comment by prasoonsoni** [comment]
Ya Sure @rishuyadav I'll remove it.

**Pull request merged**
