### PR TITLE
added repositories screen dark mode

### PR DESCRIPTION
**Pull request by V9vek**
Hey @gaganmalvi 👋🏼 
I saw issue #26 regarding `dark mode` to be implemented in the `Repositories Screen` when we apply dark mode in our device as a whole
I saw the code of the person assigned to it, but he directly applied the dark mode colors, which will result in `Repositories Screen` always in dark mode and does not change to light mode when we switch mode of the system

So, I proposing the code for the desired thing that you guys want
Take a look and review the code by checking it on your device

Thanks

### CODE REVIEW

**Comment by V9vek** [comment]
https://user-images.githubusercontent.com/40730402/135847428-837be682-e06b-4f54-a057-2e8b9bcc8e1b.mp4

Check out the sample video for the desired changes I made 

If you want any changes regarding colors or something, do let me know ☺️

**Comment by gaganmalvi** [comment]
Lgtm, great work! :))
Will merge, happy Hacktoberfest!
PS. What phone are you using? xD

**Comment by V9vek** [comment]
Thanks for the merge ☺️ 
I am using emulator `Pixel 4 API 30`

**Comment by gaganmalvi** [comment]
I thought you were testing on real hardware 😆

**Comment by V9vek** [comment]
I tested on the real device too but didn't record that
If you need any changes regarding colors or something do let me know 

Thanks and please add the required tags for hacktober-fest ☺️

**Comment by gaganmalvi** [comment]
Oh I forgot, it's done now. Thanks for the contribution, and happy Hacktoberfest! 
Do check out our [Forktober Discord](https://discord.gg/h6zqfCgW) for some cool stuff :))

**Pull request merged**
