### PR TITLE
Added Bottom Sheet fragment showing followers and following.

### PR DESCRIPTION
**Pull request by prasoonsoni**
## Followers
Screenshot_20211005-180057_GitPositive
## Following
Screenshot_20211005-180103_GitPositive

When you click any user card it will redirect you to the user's github.

### CODE REVIEW

**Comment by gaganmalvi** [comment]
Please reduce the "bug fix commits" to one, and fix the merge as well.

**Comment by prasoonsoni** [comment]
I don't have any write access to resolve conflicts.

**Comment by DarthBenro008** [comment]
Hi @prasoonsoni , please refrain from opening and closing various Pull Requests for a single issue, you can always make changes and squash your commits in the same Pull Requests (any changes to your branch will be reflected in the Pull Request too!)

Please refer help to squash commits (https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)

**Comment by prasoonsoni** [comment]
Ok, I'll take care of this in the further PR's.

**Pull request closed without merging**
