### PR TITLE
Added Dark and Light Mode, Enhanced UI, Added Loading Dialog, Added validations for empty TextBox, Changed Fonts, Added Custom Cursor,

### PR DESCRIPTION
**Pull request by prasoonsoni**
### 1. UI Changes
- Dark Mode - Before the app consist of only dark mode with some color glitches. Added Some color for dark mode.
- Light Mode - The app was not having any light mode. So, I added color for light mode also.
- Constraint Issue - Views were not properly constraint. Fixed that Issue.
- Font - Changed Font Styles.
- Loading Dialog - Added Loading Dialog when Loading User Profile Data.
- Enhanced the UI as much as possible.
### 2. Code Changes
- Validations - Added Validations for checking if edit text is empty or not.
- Toast - Added Toast Messages when there is an error.
### Screenshots
1. Dark Mode
image
image
2. Light Mode
image
image

### CODE REVIEW

**Review by DarthBenro008 — APPROVED** [review]
LGTM! Thank you for this! 🎉  

Happy Hacktoberfest! 😃

**Comment by prasoonsoni** [comment]
Thank You 😃

**Comment by gaganmalvi** [comment]
Lovely, merging.

**Comment by gaganmalvi** [comment]
Thank you for your contributions, and a happy Hacktoberfest!

**Pull request merged**
