### PR TITLE
Enhanced dashboard UI for issue #18

### PR DESCRIPTION
**Pull request by SiddyDevelops**
I have made UI changes as per the requirement, in addition I have also made the Navigation bar -> swipe from below visible which make the UI more responsive. If you like my work then please do add ```hacktober-accepted``` label. Thank you.

### CODE REVIEW

**Comment by gaganmalvi** [comment]
I was very busy the past few days, and I apologize for not coming back earlier. Will test it asap.

**Comment by gaganmalvi** [comment]
Looks very good to me, very simple and minimalist. Albeit, there's a small issue I'd like you to check out - 
image
Could you please try aligning the left card with the upper card?

**Comment by SiddyDevelops** [comment]
> Looks very good to me, very simple and minimalist. Albeit, there's a small issue I'd like you to check out - 
> image
> Could you please try aligning the left card with the upper card? 

Sure, I'll make the required asap thank you.

**Comment by SiddyDevelops** [comment]
Since the PR #61 has merged, my app is crashing, before that merge it wasn't crashing.
Hence, I am unable to make the required changes, also the only change which is required is to just remove the ```6dp margin-start``` from ```activity_main.xml``` for the first ```linearLayout``` of the ```Followers``` cardItem.
I am getting the following error: 
```
rocess: org.acmvit.gitpositive, PID: 3430
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
        at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:195)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:501)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:442)
        at androidx.room.util.DBUtil.query(DBUtil.java:83)
        at org.acmvit.gitpositive.local.UserDao_Impl$2.call(UserDao_Impl.java:75)
        at org.acmvit.gitpositive.local.UserDao_Impl$2.call(UserDao_Impl.java:72)
        at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by gaganmalvi** [comment]
Perhaps this could help you: https://stackoverflow.com/questions/44543608/room-cannot-verify-the-data-integrity-in-android

**Comment by gaganmalvi** [comment]
Most likely seems like an environment issue. If you want, I'll help you out with testing the app on real hw - ping me on @BigChadCat on Telegram, and I'll be glad to help you out.

**Pull request merged**
