### PR TITLE
Added Error Screen when Internet is not connected.

### PR DESCRIPTION
**Pull request by prasoonsoni**
1. When the internet is connected.
Screenshot_20211003-215619_GitPositive
2. When the Internet is not connected.
Screenshot_20211003-215639_GitPositive
Solved Issue #23 .

### CODE REVIEW

**Comment by prasoonsoni** [comment]
Could you please have a look at this?

**Comment by rishuyadav** [comment]
Great implementation, the animation also looks gr8 for now, if there is  any change in plan to stick with the proposed design in the issue #23 , it could be done later, lgtm for now, merging

**Comment by rishuyadav** [comment]
Thanks for contributing @prasoonsoni

**Comment by prasoonsoni** [comment]
Welcome @rishuyadav 👍🏻

**Pull request merged**
