### PR TITLE
Fix Issue : 55

### PR DESCRIPTION
**Pull request by rooparsh**
This PR restructures the project hierarchy and make the code more modular 
Addresses the issue [Link](https://github.com/ACM-VIT/gitpositive/issues/55)

### CODE REVIEW

**Comment by rooparsh** [comment]
@DarthBenro008 if you take a pull of this branch and compare with main branch, you will understand what I am saying

**Comment by gaganmalvi** [comment]
I'm sorry I was AFK for the past few days, I will check asap.

**Comment by ersascape** [comment]
Can you fix the merge conflicts?
I'll go ahead with the merge

**Comment by rooparsh** [comment]
@gaganmalvi Conflicts resolved

**Comment by rishuyadav** [comment]
Looks good and organized, thanks for contributing

**Pull request merged**
