### PR TITLE
UI Enhancements

### PR DESCRIPTION
**Pull request by SiddyDevelops**
Made all the required changes.

### CODE REVIEW

**Comment by gaganmalvi** [comment]
Wouldn't some changes in this break light theming?

**Comment by SiddyDevelops** [comment]
> Wouldn't some changes in this break light theming?

I am not sure what you mean. I did the UI only for dashboard.

**Comment by gaganmalvi** [comment]
I'll be back after testing this PR.
Thanks for the contributions!

**Comment by SiddyDevelops** [comment]
> Here if you put only white it will cause a problem in light mode, as the background color in the light mode is white so the text will not be visible.

Okay I'll resolve the issue. Instead of hardcoding the white string, I'll declare a color attribute which can later be manipulated with the change in theme.

**Review by SiddyDevelops — COMMENTED** [review]
I have replaced the hardcoded color with a color attribute, but to make it work I had to assign a ```textColor="@color/white"``` in the xml. Now it works as expected and required. Thank you.

**Comment by ersascape** [comment]
There are some conflicts, please resolve asap so I can merge this as well.

**Comment by SiddyDevelops** [comment]
> There are some conflicts, please resolve asap so I can merge this as well.

You can review the changes and merge. Thank you!

**Pull request merged**
