### PR TITLE
Fix status bar icon color on light background

### LINKED ISSUE #9: Status Bar not distinctly visible
Status Bar color is set as that of bg_color(#ffffff) white which is same as the default status bar icon colors, so icons are not visible.
Check below image for reference.

image

### PR DESCRIPTION
**Pull request by UbadahJ**
Fix #9

### CODE REVIEW

**Comment by Avinaash7** [comment]
@UbadahJ 
Delete the already existing status bar color statement line, then the code is good to go.

**Comment by UbadahJ** [comment]
But why? Don't you need it white statusbar with black icons? @Avinaash7

**Comment by rishuyadav** [comment]
> But why? Don't you need it white statusbar with black icons? @Avinaash7

Hey @UbadahJ the reason why @Avinaash7 said so is because we were planning status bar color to be a bit different from home screen (for reference check Youtube light mode), but until further design plan we are good to go with ur commit.
Cheers 🎉

**Comment by UbadahJ** [comment]
Alright then, awaiting the merge

**Pull request merged**
